<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test Suite Add addresses</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-09-21T12:21:16</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>ecaca731-4020-4110-a9eb-a64238d2c47c</testSuiteGuid>
   <testCaseLink>
      <guid>a6b4d265-5650-420e-8eca-8ff3f14ae3fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Home/Add address</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1049828f-ec38-4230-b642-ba73b4749a8e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/spreadsheet Addresses</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f86688e5-22cd-4869-a4fc-ea68c0ca2076</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbfe9752-3bd7-4d15-88ac-2d38b366bc41</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75d14f55-35a5-4d30-80b2-e45f06ee3be6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05394250-db83-4161-a4e1-740dbfcc9ce5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>897ea17a-17dc-460f-94f2-6d759f95da78</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d453d66-8971-4580-b08f-e7fb4ece0b0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d52c54bc-ac5c-40a6-9332-fea206117fda</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3d9657f-544d-4a39-a15c-59556dfc0162</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ee32ccb-660e-4533-bcd3-ccde393ce3ea</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
